//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorites
    {
        public int Id { get; set; }
        public int MovieId { get; set; }
        public Nullable<int> RattingId { get; set; }
        public string UserId { get; set; }
    
        public virtual Movies Movies { get; set; }
        public virtual Ratting Ratting { get; set; }
    }
}
