//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Movies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movies()
        {
            this.Favorites = new HashSet<Favorites>();
        }

        int max = DateTime.Now.Year;
        public int Id { get; set; }
        [Required(ErrorMessage ="Title is required")]
        [DisplayName("Title")]
        public string Name { get; set; }
        [Required(ErrorMessage ="Select a ratting from list")]
        [DisplayName("Ratting")]
        public int RattingId { get; set; }
        [Required(ErrorMessage ="Year is required")]
        [Range(1000, 2021,ErrorMessage ="Inser a valid year")]
        public int Year { get; set; }
        [Required(ErrorMessage ="Select a genre from list")]
        
        [DisplayName("Genre")]
        public int GenreId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorites> Favorites { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Ratting Ratting { get; set; }
    }
}
